export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const DISPLAY_ALERT = "DISPLAY_ALERT";

export const SELL_ITEM_SUCCESS = "SELL_ITEM_SUCCESS";
export const SELL_ITEM_ERROR = "SELL_ITEM_ERROR";

export const REGISTER_DISPLAY_SUCCESS = "REGISTER_DISPLAY_SUCCESS";
export const LOGIN_DISPLAY_SUCCESS = "LOGIN_DISPLAY_SUCCESS";
